Add fallback path capability
fermyon/spin-fileserver pull request #27
Opened 2023-01-27 15:39 UTC by jpflueger

This pull request adds the ability to define a "fallback path" that can be used, when enabled, as a 200 OK response instead of a 404 when a file is not found. This can be used with front-end single-page applications to allow the application to do partial view routing based on the URL.

Created as a possible resolution to #26 

# Notes
- Because it uses an environment variable, I had to add `--test-threads 1` so that the test I added to verify the functionality does not alter the behavior of another test.
- I'm pretty new to Rust so any and all critical feedback here will help me learn

Thanks for looking!

Signed-off-by: Justin Pflueger <justin.pflueger@fermyon.com>

2023-01-29 19:23 UTC, itowlson commented
Don't use an environment variable, because then it won't work in Cloud.

Instead, use a component config setting:

```
[[component.config]]
fallback_path = "/foo"
```

and access it as:

```
spin_sdk::config::get("foo")
```

(falling back to existing 404 ciode if the config entry is not present)

2023-01-29 19:29 UTC, itowlson commented
Actually I guess it works in cloud if you set the environment variable directly on the component... I'd still recommend config to reduce the risk of "it worked on my machine (because I had an ambient environment variable)."

2023-01-29 20:26 UTC, itowlson requested changes
The logic looks fine but I'd like to see a more natural structure to the code.  The current code makes "is there a fallback path" the first and primary decision point, after which the entire code path forks.  To me "is there a fallback path" is more naturally something we check when we've tried and failed to serve the normal path.

As mentioned elsewhere, I'd also suggest changing to use the Spin config system rather than an environment variable, though now I remind myself of the config system it does seem more set up for cases where the key must *always* be present, so I'm starting to have reservations about that...!

2023-01-29 20:26 UTC, itowlson commented on src/lib.rs
> +    let read_result = match std::env::var(FALLBACK_PATH_ENV) {
This construct forces you to have two entirely separate code paths depending on whether there is a fallback or not.  Whereas really you _always_ want to try to serve the file, and _only if it doesn't exist_ use the fallback path.  (You also end up with oddities like printing a "Cannot read env var" error message on EVERY request, even successful ones.)

So I would suggest structuring this within the existing structure along the lines of:

1. Try to read the requested file as normal
2. If that fails, consult the fallback setting
3a. If there is no fallback, return `not_found()`.
3b. If there is, try to read the fallback file

2023-01-30 17:30 UTC, jpflueger commented on src/lib.rs
> +    let read_result = match std::env::var(FALLBACK_PATH_ENV) {
Okay so I think I have the code re-arranged but I'm running into a problem when using `spin_sdk::config::get()`. When I try to run `make test` it fails with a linking error because there is not implementation for my machine's architecture. I'm not sure how to get around with without adding a compiler directive (like `#if ARM64` in C#). It seems like the decision is either: use environment variable to keep unit tests, ditch unit tests to use `spin_sdk::config::get`, or re-write unit tests as "integration tests" that could be run via cli with `spin up &; make test-int`. Is there something I'm missing here?

2023-01-30 19:50 UTC, itowlson commented on src/lib.rs
> +    let read_result = match std::env::var(FALLBACK_PATH_ENV) {
Oh, interesting re cache control.  It undoubtedly predates the config service (and may even be inherited from WAGI).  Maybe we should look at changing that (in a separate PR).  Or maybe we should be consistent for now and then change them together in some future version.  I am happy to withdraw my suggestion for `config`, but in that case we would definitely need to document how to get the fallback setting into the Cloud!

2023-01-31 14:02 UTC, jpflueger commented on src/lib.rs
> +    let read_result = match std::env::var(FALLBACK_PATH_ENV) {
Okay, I updated the readme to include instructions on setting the fallback path as an environment variable. 

The unit tests seem, to me, more like integration tests as they are directly using the trigger function. If we were to switch environment variables to config variables, the unit tests would have to be removed because we can't use the spin-sdk on anything but the wasi32-wasm target. So I think we should add two issues:

1. Re-write unit tests as integration tests
2. Change environment variables to use config variables

For now, I think we should keep it as an environment variable and address the other issues separately. Thoughts?

2023-01-31 19:59 UTC, itowlson commented on src/lib.rs
> +    let read_result = match std::env::var(FALLBACK_PATH_ENV) {
sold!

2023-02-01 18:16 UTC, jpflueger commented on src/lib.rs
> +    let read_result = match std::env::var(FALLBACK_PATH_ENV) {
Great! I created issues #28 and #29 to capture that. Anything else that I need to do for this PR?

2023-02-01 19:44 UTC, itowlson approved these changes

2023-02-01 19:44 UTC, itowlson commented
No, you've even pre-empted me by writing docs!  :shipit:

2023-02-01 21:26 UTC, merged

2023-02-20 12:13 UTC, mikkelhegn commented
Should we release a v0.0.2 based on this?