Improved path resolution
fermyon/spin-fileserver pull request #35
Opened 2023-04-14 18:18 UTC by jpflueger

Last week we discovered a bug in the fileserver that would result in a panic if we pass an empty string into the `File::open` function. For instance, if the fileserver is mounted to the `/admin/...` path and the user tries to navigate to `http://127.0.0.1/admin` the fileserver would panic. @dicej suggested checking if the file exists before opening the file for read instead of using errors for control flow. I added a function that attempts to resolve a path to a file that exists before trying to open that path for read. This should eliminate the need to retry reading a file after it fails.

2023-04-14 18:36 UTC, dicej approved these changes

2023-04-16 20:23 UTC, itowlson requested changes
I'm a bit puzzled by the suggestion not to use errors for control flow - I always thought that for I/O we were _precisely_ meant to use errors for control flow because otherwise you get race conditions - but in the Spin file server context the set of files is going to be static enough that it's not really an issue, and I really like the clarity that the pre-check gives us.

The change I'd like it quite small, just to keep the resolved path as a path rather than converting to and from string (and causing a panic if that conversion goes awry).  Otherwise looks good - thanks!

2023-04-16 20:23 UTC, itowlson commented on src/lib.rs
> +            Some(path.to_str().unwrap().to_string())
Keep it as a `PathBuf` throughout rather than converting to string with potential panic.  (I guess this requires a change to the `read` signature but I don't _think_ it should affect the body... if it turns into a big change then never mind!)

2023-04-16 20:23 UTC, itowlson commented on src/lib.rs
> +        // still haven't found a file, override with the user-configured fallback path
nit/typo

```suggestion
        // if still haven't found a file, override with the user-configured fallback path
```

2023-04-17 22:15 UTC, dicej commented
@itowlson There's no issue in general with using errors for control flow, and I agree that from a race condition perspective it's preferable.

In this particular case, though, Wasmtime's WASI Preview 1 implementation has a bug where it fails to raise an error when it should, allowing the application to open a non-existent file as if it exists, pointing the underlying descriptor at the parent directory of the would-be file, and only later raising an error when the app tries to read from that file-but-really-a-directory.  The plan is to fix that bug for Preview 2, which will break `spin-fileserver` if we don't make any changes.

2023-04-17 22:16 UTC, itowlson commented
Ouch!  Thanks for explaining @dicej!

2023-04-19 15:21 UTC, jpflueger commented
@itowlson sorry, I may have mis-relayed @dicej's intent from slack. Makes sense that we would use errors for control flow in an IO context when you put it that way. I'm happy to revert and try another way if that is preferable and handle the empty filename in another way?

2023-04-19 20:29 UTC, itowlson commented
@jpflueger Nah, Joel's explanation makes sense and it's no biggie in the relatively static Spin context.  Let's just make the PathBuf change (or consciously decide not to) and ship it _grin_

2023-04-20 02:41 UTC, jpflueger commented on src/lib.rs
> +            Some(path.to_str().unwrap().to_string())
Done! I had to change the error message to use `.display()` and I'm not entirely sure that's the right thing to do, just followed the compiler's hint. Formatting was the result of `cargo fmt`. Let me know if I need to change further.

2023-04-20 02:42 UTC, itowlson approved these changes

2023-04-20 02:43 UTC, itowlson commented on src/lib.rs
> +            Some(path.to_str().unwrap().to_string())
Yeah `.display()` is the one - annoying because it tends to make `cargo fmt` go "let me spread your simple message across 3 lines" but it is what it is.  LGTM - thanks!

2023-04-20 02:48 UTC, merged